### ISSUE TITLE
Option to adjust email capabilities (multiple request)

### ISSUE THREAD

**Issue by CFMCGEE** [cf-toolsuite/cf-butler#448]
There are a few things that I'm requesting through this issue.

1.  CSV and/or JSON file to email reports
`Currently when emails are sent (say using the endpoint policy), where most endpoint are queried, they only provide a JSON file rather than a CSV file with the data attached inside. An option to specify whether or not you want a CSV or JSON file would be incredibly helpful as not everyone who would want to get these reports has time to download and JQ the JSONs. `

2. Custom email body (instead of using the body key)
`Similarly when sending emails there is more or less a default email that goes along with it outside of the body being able to be slightly modified. It would be far more helpful if an entire custom HTML file could be attached to provide more insight on that specific policy. This option be very helpful. `

3. CC email to avoid email being sent separately unless requested
`It appears that every email sent is done so separately rather than as one chuck. If there was a way to send it collectively through a caron copy, then that would be very helpful.`

**Comment by pacphi** [comment]
Was on holiday when this was first posted. So apologies for the delay in responding. 

For bullet 1 - wouldn't it simple enough to use `jq` to produce `csv` report formats? See https://richrose.dev/posts/linux/jq/jq-json2csv/.

For Bullet 2 - this is a rather simple feature to implement. The Java Mail config is geared to send a multi-part email. I'm assuming you would like ability to add one or more other custom defined attachments to the email (e.g. an HTML doc).  We'd need to update the email template config to support that.

Bullet 3 is a bit nuanced. I'd like to understand your specific use case a bit better.

**Comment by CFMCGEE** [comment]
@pacphi 

For **bullet 1**: The reason I'm requesting for it to be added as a feature is so that it can be done automatically by CF-Butler. I could download the JSON files and then just run a JQ command but those who may request the reports (higher management) may not want to do that. 

For **bullet 2/3**: The use case is just to make it a little more neat. A singular email with all of the individuals needed being in the same chain makes it easier to respond back and discuss based off the policy that has been executed.

**Comment by pacphi** [comment]
I've started a [new branch](https://github.com/cf-toolsuite/cf-butler/tree/email-notification-feature-enhancements) to add these features.

I believe I've satisfied the **first bullet** of this request as of this [commit](https://github.com/cf-toolsuite/cf-butler/commit/9d3290cfa87b1dd7ffb6bdf0f1f33444d246de2f).

I'll work on adding cc: capability next.

**Comment by pacphi** [comment]
I've added /cc and /bcc fields to the `EmailNotificationTemplate` and plumbed the notifier implementations so now all policies benefit from the ability to optionally define these types of recipients, as of [this commit](https://github.com/cf-toolsuite/cf-butler/commit/5997880578a6ca6d9cfabe8691e4aa28461fe9be).

**Comment by pacphi** [comment]
Seeking clarification on **bullet 2**. Does the ability to specify one or more additional custom attachments in template suffice?

**Comment by CFMCGEE** [comment]
@pacphi 

Here an example of what I was thinking. 

![image](https://github.com/user-attachments/assets/4c0ae01d-c7ca-4d99-b887-be1aa2c5b82f)

**Comment by pacphi** [comment]
I simplifed the email template. I believe it will have the desired effect.  Something else that could be interesting is the ability for you (and others) to override the default template with one of your own design.  I'm going to work on plumbing that and update the documentation with an example usage.

**Comment by pacphi** [comment]
For **bullet 3**, these two commits ought to satisfy your requirements:

* Simplify exisiting default template - https://github.com/cf-toolsuite/cf-butler/commit/0e2968e208b61422482375d1a504993917279a3c
* Allow for overriding the default template - https://github.com/cf-toolsuite/cf-butler/commit/7d6b05e702c81530850634560f2581595f20892d

**Comment by pacphi** [comment]
Revisiting **bullet 1**.

Trying to convert arbitrary nested JSON structures to comma-separated-value records is complicated.  Doing it for simple JSON arrays is trivial.  But once you attempt to parse nested structures -- and many of the available endpoints are -- what do you choose to emit as a collection of columns and rows? Do you walk a structure until you find the first leaf (e.g., a JSON array) and emit each leaf as a separate file? It gets gnarly fast.

Spitballing here... perhaps one could optionally define triplets, like:

* `String endpoint`
* `String jsonPathExpression`
* `boolean flag`

We'd adapt the converter impl to look something like below (employing Jayway's JsonPath library, so we can specify jq-like path expressions to extract the nested bits we might want). The flag is there to attempt conversion from JSON array to CSV records.  The implementation would attempt conversion only if the path matches and the resulting field-value is a JSON array.  Otherwise, it emits the JSON string.

```java
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.jayway.jsonpath.JsonPath;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVPrinter;

import java.io.FileWriter;
import java.io.IOException;
import java.util.*;

public class JsonToCsvConverter {

    public static void main(String[] args) {
        String jsonString = "{ ... }"; // Your JSON string here
        String jsonPathExpression = "$.applications"; // Your JSON path expression here

        try {
            // Parse JSON
            ObjectMapper objectMapper = new ObjectMapper();
            JsonNode rootNode = objectMapper.readTree(jsonString);

            // Extract data using JSON path
            Object extractedData = JsonPath.read(jsonString, jsonPathExpression);

            // Process the extracted data
            processExtractedData(jsonPathExpression, extractedData);

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private static void processExtractedData(String path, Object data) throws IOException {
        if (data instanceof List) {
            // This is an array, create a CSV file
            List<String[]> csvData = extractArrayData((List<?>) data);
            String fileName = generateFileName(path);
            writeToCSV(fileName, csvData);
        } else {
            // Emit JSON value
            System.out.println("Extracted JSON value: " + data);
        }
    }

    private static List<String[]> extractArrayData(List<?> array) {
        List<String[]> data = new ArrayList<>();

        // Extract headers
        Set<String> headers = new LinkedHashSet<>();
        for (Object element : array) {
            if (element instanceof Map) {
                ((Map<?, ?>) element).keySet().forEach(key -> headers.add(key.toString()));
            }
        }
        data.add(headers.toArray(new String[0]));

        // Extract data
        for (Object element : array) {
            if (element instanceof Map) {
                String[] row = new String[headers.size()];
                int i = 0;
                for (String header : headers) {
                    Object value = ((Map<?, ?>) element).get(header);
                    row[i++] = (value != null) ? value.toString() : "";
                }
                data.add(row);
            } else {
                data.add(new String[]{element.toString()});
            }
        }

        return data;
    }

    private static String generateFileName(String path) {
        return path.replaceAll("[^a-zA-Z0-9.-]", "_") + ".csv";
    }

    private static void writeToCSV(String fileName, List<String[]> data) throws IOException {
        FileWriter out = new FileWriter(fileName);
        try (CSVPrinter printer = new CSVPrinter(out, CSVFormat.DEFAULT)) {
            printer.printRecords(data);
        }
        System.out.println("Created file: " + fileName);
    }
}
```

**Comment by pacphi** [comment]
Rudimentary implementation exists now as of [this commit](https://github.com/cf-toolsuite/cf-butler/commit/f1e77816708eb72f5126c54d1be452c352350a82) taking into consideration aforementioned idea(s).

**Comment by pacphi** [comment]
All features have been implemented and merged to main. Closing issue.
